# Generated by Django 4.1 on 2022-09-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='users/ps.1.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
