# Generated by Django 4.1 on 2022-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myuser', '0002_alter_myuser_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='photo',
            field=models.ImageField(default='users/WIN_20220520_23_18_07_Pro.jpg', upload_to='users/%Y/%m/%d'),
        ),
    ]
